import Head from 'next/head'
import Image from 'next/image'
import GuruHotelLogo from '../public/guruhotel.svg'
import { styled } from '@guruhotel/aura-ui'

const NavButtonProps = {
  cursor: 'pointer',
  padding: '12px',
  paddingLeft: ' 35px',
  paddingRight: ' 35px',
  color: '#ffffff',
  borderRadius: ' 0.5rem',
  display: 'block',
  textAlign: ' center',
}

const NavButtonPrimary = styled('a', {
  ...NavButtonProps,
  backgroundColor: '#3574e3',
})

const NavButtonSecondary = styled('a', {
  ...NavButtonProps,
  backgroundColor: '#221f5d',
})

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="nav">
        <div>
          <a href="#">
            <Image
              alt="GuruHotel"
              title="GuruHotel"
              src={GuruHotelLogo}
              className="guruhotel-logo"
            />
          </a>
        </div>

        <nav className="nav__sections">
          <ul>
            <li>
              <a href="https://www.guruhotel.com/en/solutions/hotel-website">
                Hotel Website
              </a>
            </li>
            <li>
              <a href="https://www.guruhotel.com/en/solutions/hotel-manager">
                Hotel Manager
              </a>
            </li>
            <li>
              <a href="https://www.guruhotel.com/en/solutions/guest-dashboard">
                Guest
              </a>
            </li>
            <li>
              <a href="https://www.guruhotel.com/en/solutions/checkout">
                Checkout
              </a>
            </li>
          </ul>
        </nav>
        <div className="nav__buttons">
          <NavButtonSecondary role={'button'} title="Learn more">
            Learn more
          </NavButtonSecondary>
          <NavButtonPrimary role={'button'} title="Launch website">
            Launch website
          </NavButtonPrimary>
        </div>
      </div>
    </div>
  )
}
